### ISSUE TITLE
Question regarding fitStudent() and rNorm()

### ISSUE THREAD

**Issue by thestockman27** [qrmtutorial/qrm#2]
Hello, 

I am attempting to pass a larger portfolio through the 09_Standard_Methods_for_market_risk.r script.

I am wondering if you could help me better understand the issue I am getting when using the rNorm() and fitstudent() functions on a fixed income portfolio of 137 securities with roughly 2500 observations each.

Error Message:
 `Error in chol.default(scale.est) : 
  the leading minor of order 8 is not positive definite`

How might I best troubleshoot this situation?

**Comment by ajmcneil** [comment]
Not sure exactly - haven’t see that error. It sounds to me that your 137 by 137 system might be collinear or near collinear so that the covariance matrix is not positive semi-definite. The Cholesky decomposition should only work for psd matrices. I would try reducing dimensionality through some kind of factor analysis.

**Comment by thestockman27** [comment]
Looks like I had an issue with the data. Cash held in the portfolio was not supplying a CUSIP to query against in the call to bloomberg. Something in my for loop must've been getting duplicated to cause that error message. Sorry for the false alarm, I should know better than to trust code I have written past 1AM... :)

While I have you, I cannot thank you all enough for the efforts you gave to create the book and this accompanying depository.  As a first year Research Analyst at a small firm, it has been invaluable to me!

**Comment by ajmcneil** [comment]
Thanks for this kind feedback. Good to hear that you find it useful. 
Alex McNeil
